2018-05-25 03:20:31,531 - root - ERROR - Error occurred
2018-05-25 03:24:07,058 - root - ERROR - Error occurred
2018-05-25 03:28:26,791 - tornado.application - ERROR - Uncaught exception POST /login (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/login', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1187, in handle_yield
    self.future = convert_yielded(yielded)
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1329, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
tornado.gen.BadYieldError: yielded unknown object <generator object post at 0x7fc8117ab1a8>
2018-05-25 03:28:26,805 - tornado.access - ERROR - 500 POST /login (::1) 14.51ms
2018-05-25 03:31:29,506 - tornado.application - ERROR - Uncaught exception POST /login (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/login', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1187, in handle_yield
    self.future = convert_yielded(yielded)
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/functools.py", line 803, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1329, in convert_yielded
    raise BadYieldError("yielded unknown object %r" % (yielded,))
tornado.gen.BadYieldError: yielded unknown object <generator object post at 0x7fcbde7112b0>
2018-05-25 03:31:29,508 - tornado.access - ERROR - 500 POST /login (::1) 2.73ms
2018-05-25 03:32:04,671 - tornado.application - ERROR - Uncaught exception POST /login (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/login', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/home/feynman/Programs/feynmen-base/lib/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/home/feynman/Programs/feynmen-base/LoginModule/login.py", line 55, in post
    password = post_arguments.get("password", None)
NameError: name 'post_arguments' is not defined
2018-05-25 03:32:04,672 - tornado.access - ERROR - 500 POST /login (::1) 2.23ms
2018-05-25 03:32:49,805 - root - ERROR - MotorCollection object is not callable. If you meant to call the 'find_one' method on a MotorCollection object it is failing because no such method exists.
2018-05-25 03:34:28,974 - root - ERROR - MotorCollection object is not callable. If you meant to call the 'find_one' method on a MotorCollection object it is failing because no such method exists.
2018-05-25 03:35:56,644 - root - ERROR - MotorCollection object is not callable. If you meant to call the 'find_one' method on a MotorCollection object it is failing because no such method exists.
2018-05-25 03:36:12,828 - root - ERROR - MotorCollection object is not callable. If you meant to call the 'find_one' method on a MotorCollection object it is failing because no such method exists.
2018-05-25 03:37:02,268 - root - ERROR - MotorCollection object is not callable. If you meant to call the 'find_one' method on a MotorCollection object it is failing because no such method exists.
2018-05-25 03:42:38,382 - root - ERROR - user doesnt exist
